# This comment is indented at the wrong level
- name: DEPLOYING SNMP CONFIGURATIONS ON IOS AND JUNOS
  hosts: iosxe,vmx

  vars:
    ansible_connection: network_cli
    vendor_commands :
      ios: |
        snmp-server community ntc-team RO
        snmp-server location FL_HQ
        snmp-server contact JAMES_CHARLES

  tasks:
    - name: Task 1 - ensure snmp commands exist on ios and vmx devices
      cli_config:
        config: "{{ vendor_commands[ansible_network_os] }}"

    - cli_config:
        msg: A task without a name, so lazy!
